### ISSUE TITLE
Improve support for Consul deployments on clusters with less than 3 nodes

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery-consul#1]
**Issue:** A Consul deployment on a cluster with less than three nodes finds "consul-server" pods stuck in a Pending state. 

Example of a two node system: 

```
➜  ~ k get pods -n consul
NAME                                                              READY   STATUS    RESTARTS   AGE
consul-consul-6jkw6                                               0/1     Running   0          24m
consul-consul-connect-injector-webhook-deployment-5579b766zpmwm   1/1     Running   0          24m
consul-consul-server-0                                            0/1     Pending   0          24m
consul-consul-server-1                                            0/1     Pending   0          24m
consul-consul-server-2                                            0/1     Pending   0          24m
consul-consul-test-1klet                                          0/1     Error     0          24m
```

The consul servers fail to start:

 ```Events:
  Type     Reason            Age                 From               Message
  ----     ------            ----                ----               -------
  Warning  FailedScheduling  47s (x21 over 26m)  default-scheduler  pod has unbound immediate PersistentVolumeClaims
```

**Request:** Provide flag to nullify "consul-server"s Pod anti-affinity requirement at https://github.com/layer5io/meshery-consul/blob/master/consul/config_templates/consul.yaml#L615.

@nicholasjackson @eveld, regarding this issue, it seems we’ll need to `null` the podAntiAffinity requirement in the consul pod spec to allow deployments onto lesser than 3 node clusters. Is that right? https://www.consul.io/docs/platform/k8s/helm.html#v-server-affinity Are there any other solutions we should consider for small deployments?

**Comment by mgfeller** [comment]
I suggest we close this issue and incorporate the fix in #2 , setting both server.replicas and server.bootstrapExpect to 1 in the Helm values file used to generate the manifests.
