### ISSUE TITLE
[CI] Slack notifier failing (based on use of env var)

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery-consul#147]
**Description**
The workflow to notify slack on star of a repo is failing. See https://github.com/layer5io/meshery-consul/actions/runs/690457625

**Suggested Solution**
See https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/

**Comment by chinmaym07** [comment]
@leecalcote sir I want to try this.!
