### ISSUE TITLE
README: Add hyperlinks to badges

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery-consul#20]
**Description**
Some of the badges in this repos readme are missing informative hyperlinks.

**Desired Behavior**
The badges (and their links) that are used in the [Meshery repo's README](https://github.com/layer5io/meshery/blob/master/README.md) are a great example of how the badges in this repo can be improved.

**Comment by lmilekic** [comment]
Seems like my PR is hitting some build issues, are those lint failures expected? 😄

**Comment by leecalcote** [comment]
@lmilekic great question. Yes, those are pre-existing issues that hopefully other contributors are working on knocking out. Your help on this issue (and any others) is most appreciated! 

// @ashiscs @gunjanmimo

**Comment by leecalcote** [comment]
Related lint issue - https://github.com/layer5io/meshery-consul/issues/8
