### ISSUE TITLE
[Install] Use helm to deploy Consul 1.9.1

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery-consul#37]
**Enhancement Description**
The Consul deployment process uses Kubernetes manifests currently.

**Related Challenges**
Helm is a more robust way of deploying Consul and will offer easier ways to allow the user to configure their Consul deployment. Not all, but some other Meshery adapters benefit from use of helm deployments (shared code here may be useful).

**Resources**
- https://learn.hashicorp.com/consul/kubernetes/kubernetes-deployment-guide

**Comment by mgfeller** [comment]
Suggest that this is done after #98

**Comment by Aisuko** [comment]
We already have the chart for `meshery-consul`, we can close the issue https://artifacthub.io/packages/helm/meshery/meshery

**Comment by mgfeller** [comment]
@Aisuko could you please elaborate? Consul is not deployed using Helm. I planned to work on that as soon as Helm functionality was available in meshery-adapter-library.

**Comment by mgfeller** [comment]
@Aisuko are you referring to a chart to deploy the `meshery-consul` adapter? This issue is about deploying Consul.

**Comment by Aisuko** [comment]
@mgfeller You are right. We should reopen the issue. But for my personal experiences, maybe better to choose a more native way,  for example, like `Linkerd2` and `OSM` service-mesh application use `helm.sh/v3` to generate the manifest inside the `pkg` package. But those function I said above were private, that means can not import by other projects.  Related https://github.com/linkerd/linkerd2/discussions/4467

**Comment by mgfeller** [comment]
@Aisuko I was referring to https://github.com/layer5io/meshkit/pull/23 regarding Helm support. Did you see that?

**Comment by Aisuko** [comment]
@mgfeller For my personal, I'd like to import the service-mesh applications source code `pkg` to render the multiple version manifest of the service-mesh application rather than download the chart, because we need stability, but we do not know if the upstream release new charts with some breaking change like `istio v1.6` can not directly upgrade to `v1.7`(maybe `v1.7` -> `v1.8`). I'd like to maintain the stable charts repo for all the service-mesh application(like the system-chart repo under rancher org) under layer5, but it was not achieved for some reasons. But, it's good to see we have this feature.

**Comment by mgfeller** [comment]
@Aisuko not quite sure I understand completely, but I agree we need stability. Also, different meshes package and deploy differently, meaning that it is difficult to generalize. Breaking changes and backward compatibility are also handled differently wrt versioning, as you mention, so we have to consider that for each mesh individually. 

The Consul Helm charts do not follow the Consul versioning, and there is not a distinct Helm chart version for each minor Consul release. Different values-files for specific Helm chart versions and distinct configurations is what I had in mind here. Not all configurations can be applied using Helm upgrade, some require a fresh install.

You raise a point I wondered about: does Meshery intend to provide upgrades and upgradeable configurations? How do we check the prerequisites for configuration changes?

Should we always just provide the latest version or all supported versions, or what? It will not work for all meshes to just download binaries or Helm charts (with default values) from the vendor.

A plan, requirements, intentions or similar in the design doc would be nice - don't remember having seen that...

**Comment by Aisuko** [comment]
We would like to handle at least 3 stable versions of the service-mesh applications and the latest version of edge, it's our original plan but it not came true(We can maintain the repo like https://github.com/rancher/system -charts/tree/dev-v2.5/charts/rancher-istio). If I remember right I wrote the documentation but not sure where it saved on. @leecalcote Any detail or need to correct please comment us. 

@mgfeller You let me think the things, Should we provide upgrades and upgradeable for the service-mesh applications?

**Comment by mgfeller** [comment]
> @mgfeller You let me think the things, Should we provide upgrades and upgradeable for the service-mesh applications?

@Aisuko not sure, let's ponder this for a bit. It also means a commitment to maintain that in the future, meaning that we think we have time and contributors to support that.

**Comment by mgfeller** [comment]
> We would like to handle at least 3 stable versions of the service-mesh applications and the latest version of edge, it's our original plan but it not came true(We can maintain the repo like https://github.com/rancher/system -charts/tree/dev-v2.5/charts/rancher-istio). If I remember right I wrote the documentation but not sure where it saved on. @leecalcote Any detail or need to correct please comment us.

This would be quite a commitment.

**Comment by mgfeller** [comment]
Using this issue to implement installation of Consul 1.9.1 using Helm, changing title of this issue to reflect that.

**Comment by mgfeller** [comment]
@kumarabd @utkarsh-pro
Using the Helm new functionality in `meshkit`, I apply the Helm chart with custom values file to deploy Consul 1.9.1. Works fine when I run the adapter in-process.

However, when I run it using `mesheryctl`, i.e. as container, it fails with:

```
meshery-consul_1  | {"app":"consul-adapter","caller":"level.go:63","code":"1008","level":"error","long-description":"Error applying operation.Error applying helm chart: Error applying helm chart: Kubernetes cluster unreachable: Get \"https://192.168.49.2:8443/version?timeout=32s\": x509: certificate signed by unknown authority","probable-cause":"None","severity":1,"short-description":"None","suggested-remediation":"None","ts":"2020-12-29T20:54:32.270253693+01:00"}
```

Deploying a manifest works just fine. 

Would be nice if you could shed some light on this, I'm at a loss (after some hours trying to understand and fix this...).

**Comment by utkarsh-pro** [comment]
> @kumarabd @utkarsh-pro
> Using the Helm new functionality in `meshkit`, I apply the Helm chart with custom values file to deploy Consul 1.9.1. Works fine when I run the adapter in-process.
> 
> However, when I run it using `mesheryctl`, i.e. as container, it fails with:
> 
> ```
> meshery-consul_1  | {"app":"consul-adapter","caller":"level.go:63","code":"1008","level":"error","long-description":"Error applying operation.Error applying helm chart: Error applying helm chart: Kubernetes cluster unreachable: Get \"https://192.168.49.2:8443/version?timeout=32s\": x509: certificate signed by unknown authority","probable-cause":"None","severity":1,"short-description":"None","suggested-remediation":"None","ts":"2020-12-29T20:54:32.270253693+01:00"}
> ```
> 
> Deploying a manifest works just fine.
> 
> Would be nice if you could shed some light on this, I'm at a loss (after some hours trying to understand and fix this...).

Hi @mgfeller, the fix would be adding the following in the main.go
```golang
err = os.Setenv("KUBECONFIG", path.Join(
		config.KubeConfigDefaults[configprovider.FilePath],
		fmt.Sprintf("%s.%s", config.KubeConfigDefaults[configprovider.FileName], config.KubeConfigDefaults[configprovider.FileType])),
)
```
We set the env variable here so that it can be dynamic and doesn't have to be hardcoded in the Dockerfile. Fewer things to maintain 🙂.

The reason for the issue: Helm library internally expects this env variable to be available so that it can use kube config internally to communicate with the kubernetes server. In the consul adapter this variable was not set.

This issue didn't show up in other adapters because we set this env variable in adapters like istio (because istioctl expects it), osm (because osmctl expects it, probably because they also internally use helm libraries) and traefik (because traefik uses exact same function).

I hope this fixes the issue. I tried running it on my system after adding the variable and it worked fine. My configuration:
```
 ///////////////////////////////
Kubernetes Cluster: KinD
///////////////////////////////
NAME="Manjaro Linux"
ID=manjaro
ID_LIKE=arch
BUILD_ID=rolling
PRETTY_NAME="Manjaro Linux"
ANSI_COLOR="32;1;24;144;200"
HOME_URL="https://manjaro.org/"
DOCUMENTATION_URL="https://wiki.manjaro.org/"
SUPPORT_URL="https://manjaro.org/"
BUG_REPORT_URL="https://bugs.manjaro.org/"
LOGO=manjarolinux
```

**Comment by utkarsh-pro** [comment]
On another thought, I think we should either document that `applyHelmChart` needs kubeconfig env variable to be set or we should make it explicit by making kubeconfig path as a parameter to this function. Any suggestions @mgfeller @kumarabd?

**Comment by kumarabd** [comment]
@utkarsh-pro possible to set this by default in the library?

**Comment by mgfeller** [comment]
> Hi @mgfeller, the fix would be adding the following in the main.go

Hi @utkarsh-pro, thanks for the fine and detailed feedback. It sounds familiar, I think I read about this when I looked into using Helm the first time a couple of months ago. Obviously and unfortunately, I didn't remember that. What confused me (subconsciously :wink: ) is probably that it looks like Helm picked up some information, and all of kubeconfig looks to be passed to Helm...

**Comment by mgfeller** [comment]
@utkarsh-pro @kumarabd I think it should be documented :+1: regardless of how it is implemented. One sentence or two would be enough (and could have saved a few hours' work). This particular env var is used / required by many tools, so I'm not quite sure making the path an explicit parameter and then defining the env var in the function is the optimal solution. 

Setting it in the library might be confusing, as kubeconfig can be set by any adapter (KubeconfigHandler), then what?

What about an init/preflight-check function that would verify that the env var is declared, and other things? Like checking for required directories, and possibly create them if they do not exist. This would make the prerequisites explicit.

**Comment by mgfeller** [comment]
Another point to consider is what to do if the environment variable already exists. What I did now was to append the new path if the variable already exists, otherwise, test will fail.
