### ISSUE TITLE
Add issue templates: bug and enhancement

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery-consul#6]
Create two issue templates in the *meshery-consul* repo by copying the meshery repo's [issue templates](https://github.com/layer5io/meshery/tree/master/.github/ISSUE_TEMPLATE).

**Comment by gunjanmimo** [comment]
i completed

**Comment by leecalcote** [comment]
Partially fixed by #10.

**Comment by leecalcote** [comment]
Completely closed by #9 and #11.
