### ISSUE TITLE
[CI] Setup ReleaseDrafter

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery-consul#70]
**Current Situation**
The [ReleaseDrafter](https://github.com/marketplace/actions/release-drafter) utility (GitHub Action) is not configured in this repository.

**Desired Situation**
- Releasedrafter should be configured to execute whenever a PR is merged to master in this repo.

**Implementation**
- Copy the [releasedrafter config](https://github.com/layer5io/meshery/blob/master/.github/release-drafter.yml) and the [releasedrafter workflow](https://github.com/layer5io/meshery/blob/master/.github/workflows/release-drafter.yml) file from the `meshery` repo and place in the `.github` folder here.

**Comment by leecalcote** [comment]
@mgfeller you're so right about the project to refactor adapters being a bigger bite than should be naturally taken for anyone fresh to the projects here.

I'm pointing out this issue as one that you might consider taking up. I figure that while you're getting warmed up to the Meshery adapter for Consul, that you might entertain this small item as a good way of getting into the contribution flow.

**Comment by mgfeller** [comment]
@leecalcote thanks, that's a good start, I can do that :-) 

It is all a matter of (available) time :-)
