### ISSUE TITLE
[Chore] Refresh issue templates

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery-consul#75]
**Description**
The [issue templates](https://github.com/layer5io/meshery-consul/tree/master/.github/ISSUE_TEMPLATE) are stale and need refreshed with a newer copy from the `meshery` repo.

**Implementation**
1. Copy the issues templates from the [.github/ISSUE_TEMPLATE]((https://github.com/layer5io/meshery/tree/master/.github/ISSUE_TEMPLATE)) folder in the `meshery` repo to the [ISSUE_TEMPLATE folder in this repository](/../../.github/ISSUE_TEMPLATE).

**Comment by tory-brown** [comment]
I want to take this up

**Comment by Ruth-ikegah** [comment]
sure @tory-brown !

**Comment by PluckyPrecious** [comment]
Hi @tory-brown, situation report please. Are you still up for this issue or we should go with the PR made to this effect?

**Comment by tory-brown** [comment]
@PluckyPrecious i got a message that it was merged. already worked on it

**Comment by PluckyPrecious** [comment]
@tory-brown it was closed because you’re already assigned, do you wish to go ahead?

**Comment by Ruth-ikegah** [comment]
Hi @PluckyPrecious it has been fixed, this repo doesn't have a PR template to reference the issue number so it didn't automatically close when her PR was merged. So I'd go ahead and close the issue
