### ISSUE TITLE
Add PULL_REQUEST_TEMPLATE.md

### ISSUE THREAD

**Issue by Ruth-ikegah** [layer5io/meshery-consul#86]
**Current Behavior**

This repository does not have a Pull request template just like our other repositories have. You can have a look at the [Layer5 repo](https://github.com/layer5io/layer5/blob/master/.github/PULL_REQUEST_TEMPLATE.md) to know what a PR template looks like.

**Desired Behavior**

Navigate to the .github folder and create a new file PULL_REQUEST_TEMPLATE.md, copy the contents of the PR template [here](https://github.com/layer5io/layer5/blob/master/.github/PULL_REQUEST_TEMPLATE.md) and paste in the new file.

---
**Contributor Resources**

- [Contributing Workflow](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING-gitflow.md)
- [Contributing Overview](https://github.com/layer5io/meshery/blob/master/CONTRIBUTING.md#documentation-contribution-flow)

**Comment by Akash-Gupta-Sudo** [comment]
I am working on this issue.

**Comment by Ruth-ikegah** [comment]
Nice @Akash-Gupta-Sudo ! You have been assigned to it
