### ISSUE TITLE
[CI] Establish Meshery Edge Release Channel

### ISSUE THREAD

**Issue by leecalcote** [layer5io/meshery-consul#96]
**Current Behavior**
See https://github.com/layer5io/meshery/issues/1270 for additional details and the https://github.com/layer5io/meshery/issues/284 epic.

**Desired Behavior**
Implement in the same fashion that has been done in layer5io/meshery repo.

**Comment by leecalcote** [comment]
@MukulMaheshwari are you able to tackle this one by end of this week? If so, please grab it.

**Comment by mgfeller** [comment]
@kushthedude is this issue fixed?

**Comment by kushthedude** [comment]
Yes
