### ISSUE TITLE
[Code] Refactor to use meshery-adapter-library

### ISSUE THREAD

**Issue by mgfeller** [layer5io/meshery-consul#98]
**Current Behavior**

This adapter is _not_ using the meshery-adapter-library.

**Desired Behavior**

This adapter is using the meshery-adapter-library.

---
**Resources**

* https://github.com/layer5io/meshery-adapter-library

**Additional Context**

The initial version of meshery-adapter-library has been developed by using code from the kuma adapter and this adapter. The code for this adapter has been refactored to use meshery-adapter-library, for verification and testing purposes. This is the issue related to that work.

**Comment by leecalcote** [comment]
Excellent. 😀

**Comment by mgfeller** [comment]
https://github.com/mgfeller/meshery-consul/tree/feature/mgfeller/98
